### ISSUE TITLE
Loading Screen Design

### ISSUE THREAD

**Issue by SilasReinagel** [EnigmaDragons/LDJam56#125]

**Comment by KamuiHand** [comment]
![loading screen icon character.png](https://zube.io/files/enigmadragons/10f16c14e8ca9582b3203be7a58ba096-loading-screen-icon-character.png)
![loading screen bg.png](https://zube.io/files/enigmadragons/cd317ac9e2c6bcbc193648dfbc40c3da-loading-screen-bg.png)
.
