### ISSUE TITLE
Main Game Logo Art

### ISSUE THREAD

**Issue by SilasReinagel** [EnigmaDragons/LDJam56#126]

**Comment by KamuiHand** [comment]
![logo.png](https://zube.io/files/enigmadragons/84e618043996d62c60cbe4d07b0297bb-logo.png)
.
-add circuit underlay

**Comment by KamuiHand** [comment]
![logo_v3.png](https://zube.io/files/enigmadragons/0f7e547a5b79bb1cdbda29d80d5d2768-logo_v3.png)
.
