### ISSUE TITLE
we need the frame without the radar circle and we need the  radar circle without the frame

### ISSUE THREAD

**Issue by ZavixDragon** [EnigmaDragons/LDJam56#247]

**Comment by KamuiHand** [comment]
![map.png](https://zube.io/files/enigmadragons/754f2445b21711d6e23c4716116ec705-map.png)

**Comment by KamuiHand** [comment]
![map.png](https://zube.io/files/enigmadragons/9a054370919365c26662f019e934841e-map.png)

**Comment by KamuiHand** [comment]
![frame wo radar.png](https://zube.io/files/enigmadragons/5cc84ef19fcad1371696427c1985f8c8-frame-wo-radar.png)

**Comment by KamuiHand** [comment]
![map.png](https://zube.io/files/enigmadragons/3aeba282e30257775f54f1bf63a03574-map.png).
