### ISSUE TITLE
Select Header Font

### ISSUE THREAD

**Issue by SilasReinagel** [EnigmaDragons/LDJam56#37]

**Comment by KamuiHand** [comment]
Header
[valorax-font.zip](https://zube.io/files/enigmadragons/82322e64ab430940e1f10ca008e25bee-valorax-font.zip)
For Alert and Defeat or Victory
[legio-sabina-font.zip](https://zube.io/files/enigmadragons/9d5545ddd38817f9fdf6ef7c15b62340-legio-sabina-font.zip)
