### ISSUE TITLE
Select Body Font

### ISSUE THREAD

**Issue by SilasReinagel** [EnigmaDragons/LDJam56#38]

**Comment by KamuiHand** [comment]
[exton-font.zip](https://zube.io/files/enigmadragons/a5106678559bf562011eddf699748213-exton-font.zip)

**Comment by KamuiHand** [comment]
100% free
[construktiv-font.zip](https://zube.io/files/enigmadragons/5b514c81c72725f74dfa3f27d2330e32-construktiv-font.zip)
