### ISSUE TITLE
UI Button

### ISSUE THREAD

**Issue by SilasReinagel** [EnigmaDragons/LDJam56#39]

**Comment by KamuiHand** [comment]
button v1
![image.png](https://zube.io/files/enigmadragons/685518f31cc05226a87d5c7ddd26198e-image.png)
button v2
![image.png](https://zube.io/files/enigmadragons/7584ea952ebef537821f872a57930989-image.png)

**Comment by KamuiHand** [comment]
![Mesa de trabajo 2.png](https://zube.io/files/enigmadragons/525da38d541bdf1ee5ec18c2e9e0dfa3-mesa-de-trabajo-2.png)
png

**Comment by KamuiHand** [comment]
![button hover.png](https://zube.io/files/enigmadragons/5df6a3c26b7907c1e3efb88243a041e9-button-hover.png) update
