### ISSUE TITLE
Looking up for cyberpunk/scifi fonts

### ISSUE THREAD

**Issue by SilasReinagel** [EnigmaDragons/LDJam56#44]

**Comment by KamuiHand** [comment]
![image.png](https://zube.io/files/enigmadragons/cb9d1751de77b615d5c1f702c2e7cfe1-image.png)
![LDJam56.png](https://zube.io/files/enigmadragons/c05b232be3a262efbc2bfb18b005ce43-ldjam56.png)

**Comment by KamuiHand** [comment]
- minimal
- tilted
- perspective
- line or filled spaces
- polygons or simple geometrics
- custom for powers?

**Comment by SilasReinagel** [comment]
@KamuiHand These are nice! Which one(s) do you like best?

You're in charge of the UI. You can make the artistic decisions for all 2D art
